{
 "title": "LLM monitoring dashbord",
 "time": { "from": "2025-06-08T04:26:49.136Z", "to": "2025-06-08T04:26:49.703Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Feedback",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  SUM(CASE WHEN feedback> 0 THEN 1 ELSE 0 END) as Thumbs_up,\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as Thumbs_down\n\nFROM feedback "
    }
   ]
  },
  {
   "title": "Relevance distribution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    relevance,\n    count(*) as count\nFROM conversations\nGROUP BY relevance;"
    }
   ]
  },
  {
   "title": "Gemini Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    SUM(gemini_cost) AS total_cost\nFROM conversations\nWHERE gemini_cost > 0\nGROUP BY timestamp\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "\nSELECT\n    timestamp as time,\n    response_time\nFROM conversations\nORDER BY timestamp \n"
    }
   ]
  },
  {
   "title": "Token usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    SUM(prompt_tokens + completion_tokens) AS total_tokens\nFROM conversations\nGROUP BY timestamp\nORDER BY timestamp DESC;"
    }
   ]
  },
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp as time,\n    question,\n    answer,\n    relevance\nFROM conversations\nORDER BY timestamp DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Model used",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    model_used,\n    COUNT(*) as count\nFROM conversations\nGROUP BY model_used;"
    }
   ]
  }
 ]
}